### ISSUE TITLE
Snowmed- HPO codes?

### ISSUE THREAD

**Issue by siebert-julien** [bruzwen/ddxplus#1]
Dear @bruzwen do you happen to have the HPO Ids or Snowmed codes for the evidence in ddxplus? This would really make your dataset reach a broader audience.

Best, JS

**Comment by bruzwen** [comment]
Hi there, unfortunately we don't have the corresponding HPO IDs or Snowmed codes for the evidences. The evidences in DDXPlus are (mostly) not standard phenotypes, but instead are more complex questions that probably can't be accurately mapped to phenotypes.

Though if you have ideas for doing that, we'd be interested to hear!

Thanks

**Comment by IbrarBabar** [comment]
@siebert-julien @bruzwen @afansi 
I am not understanding the structure of the dataset. How does the CSV link with the JSON files? I am too confused about the ground truth, whether it is PATHOLOGY or DIFFERENTIAL_DIAGNOSIS.

I need help understanding it. Anyone?

**Comment by bruzwen** [comment]
Closing this as the question is not relevant to the original issue and is answered elsewhere.
